version: '3.7'

services:

  whoami:
    image: containous/whoami
    networks:
      - traefik
    deploy:
      labels:
      - traefik.enable=true

      # Redirect all traffic on hostname whoami.konradmelzer.de to whoami
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami.rule=Host(`whoami.konradmelzer.de`)
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=cert-resolver
      - traefik.http.routers.whoami.entrypoints=websecure
      
networks:
  traefik:
    external: 
      name: traefik