version: '3.7'

services:

  whoami:
    image: containous/whoami
    networks:
      - traefik
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.rule=Host(`whoami.konradmelzer.de`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      
networks:
  traefik:
    external: 
      name: traefik