version: '3.7'

services:

  fortknox:
    image: registry/fortknox
    networks:
      - traefik
    deploy:
      labels:
      - traefik.enable=true

      # Redirect all traffic on hostname fortknox.konradmelzer.de to fortknox
      - traefik.http.services.fortknox.loadbalancer.server.port=80
      - traefik.http.routers.fortknox.rule=Host(`fortknox.konradmelzer.de`)
      - traefik.http.routers.fortknox.tls=true
      - traefik.http.routers.fortknox.tls.certresolver=cert-resolver
      - traefik.http.routers.fortknox.entrypoints=websecure
      
networks:
  traefik:
    external: 
      name: traefik