version: '3.7'

services:

  homepage:
    image: registry/fortknox
    networks:
      - traefik
    deploy:
      labels:
      - traefik.enable=true

      # Redirect all traffic on hostname fortknox.konradmelzer.de to homepage
      - traefik.http.services.homepage.loadbalancer.server.port=80
      - traefik.http.routers.homepage.rule=Host(`fortknox.konradmelzer.de`)
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=cert-resolver
      - traefik.http.routers.homepage.entrypoints=websecure
      
networks:
  traefik:
    external: 
      name: traefik